---
- hosts: localhost
  connection: local
  become: true
  vars_prompt:
    - name: git_email
      prompt: Type in your git email address
    - name: git_name
      prompt: Type in your git name
  roles:
    - ../roles/setup