---

- name: Import Microsoft Apt Signing Key
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/microsoft.asc
    mode: '0644'
    force: true

- name: Add Microsoft Repository
  apt_repository:
    filename: azure-cli
    repo: "deb [arch={{ dpkgOutput }} signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ {{ lsbOutput }} main"

- name: Update apt repositories
  apt:
    update_cache: yes

- name: Install Azure packages
  package:
    name: "{{ item }}"
    state: present
  loop: 
    - "{{ azure_packages }}"