---
- name: Import Docker Apt Signing Key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'
    force: true

- name: Get output of 'dpkg --print-architecture' for the Repository
  command: dpkg --print-architecture
  register: "dpkgOutput"

- name: Get output of '. /etc/os-release && echo "$VERSION_CODENAME"' for the Repository
  command: . /etc/os-release && echo "$VERSION_CODENAME"
  register: "osReleaseOutput"

- name: Add Docker Repository
  apt_repository:
    filename: docker.list
    repo: "deb [arch={{ dpkgOutput }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu  $(. /etc/os-release && echo {{ osReleaseOutput }}) stable"

- name: Update apt repositories
  apt:
    update_cache: yes

- name: Install Docker packages
  packages:
    name: "{{ item }}"
    state: present
  loop: 
    - docker_packages