---
- name: Install pre-requisite packages 
  package:
    name: "{{ item }}"
    state: present
  loop: 
    - "{{ prereq_packages }}"

- name: Create keyring directory
  file: 
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create .ssh directory
  file: 
    path: /home/{{ ansible_user_id }}/.ssh
    state: directory
    mode: '0600'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Get output of 'dpkg --print-architecture' for the Repository
  command: dpkg --print-architecture
  register: "dpkgOutput"

- set_fact:
    dpkgOutput={{ dpkgOutput.stdout }}

- name: Get output of 'lsb_release -cs' for the Repository
  command: lsb_release -cs
  register: "lsbOutput"

- set_fact:
    lsbOutput={{ lsbOutput.stdout }}