---
- name: Install pre-requisite packages 
  package:
    name: "{{ item }}"
    state: present
  loop: 
    - {{ prereq_packages }}

- name: Create keyring directory
  file: 
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root