---
- name: Import Hashicorp Apt Signing Key
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/keyrings/hashicorp-archive-keyring.asc
    mode: '0644'
    force: true

- name: Add Hashicorp Repository
  apt_repository:
    filename: hashicorp.list
    repo: "deb [arch={{ dpkgOutput }} signed-by=/usr/apt/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ lsbOutput }} main"
    update_cache: yes

- name: Install Terraform packages
  package:
    name: "{{ item }}"
    state: present
  loop: 
    - "{{ terraform_packages }}"